/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotell;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class hotell_form extends javax.swing.JFrame {

    /**
     * Creates new form hotell_form
     */
    public hotell_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        Hari = new javax.swing.JTextField();
        Ttl_harga = new javax.swing.JTextField();
        Bayar = new javax.swing.JTextField();
        Kamar = new javax.swing.JComboBox<>();
        Konfirmasi = new javax.swing.JButton();
        Batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOTEL INDAH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Kamar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Harga");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Hari");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Total Harga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bayar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        jPanel1.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 180, -1));

        Hari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HariKeyReleased(evt);
            }
        });
        jPanel1.add(Hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 180, -1));
        jPanel1.add(Ttl_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 190, -1));
        jPanel1.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 180, -1));

        Kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "reguler", "vip", "vvip" }));
        Kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KamarActionPerformed(evt);
            }
        });
        jPanel1.add(Kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, -1));

        Konfirmasi.setText("Konfirmasi");
        Konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonfirmasiActionPerformed(evt);
            }
        });
        jPanel1.add(Konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 130, 50));

        Batal.setText("batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });
        jPanel1.add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 130, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 513);

        setSize(new java.awt.Dimension(536, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KamarActionPerformed
        if(Kamar.getSelectedItem().toString().equalsIgnoreCase("reguler")){
            Harga.setText("200000");
        }else if (Kamar.getSelectedItem().toString().equalsIgnoreCase("vip")){
            Harga.setText("400000");
        }else if (Kamar.getSelectedItem().toString().equalsIgnoreCase("vvip")){
            Harga.setText("600000");
        }
            
    }//GEN-LAST:event_KamarActionPerformed

    private void HariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HariKeyReleased
       int harga = Integer.parseInt(Harga.getText());
       int hari = Integer.parseInt(Hari.getText());
       int totalbayar = harga*hari;
       String total = Integer.toString(totalbayar);
       Ttl_harga.setText(total);
    }//GEN-LAST:event_HariKeyReleased

    private void KonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonfirmasiActionPerformed
        int bayar = Integer.parseInt(Bayar.getText());
        int ttl_harga = Integer.parseInt(Ttl_harga.getText());
        int kembalian = bayar - ttl_harga;
        String kembali= Integer.toString(kembalian);
        JOptionPane.showMessageDialog(null,"\n Kembalian Anda : \n"+kembali);
        Kamar.setSelectedItem("pilih");
        Harga.setText("");
        Hari.setText("");
        Ttl_harga.setText("");
        Bayar.setText("");
    }//GEN-LAST:event_KonfirmasiActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
     Kamar.setSelectedItem("pilih");
        Harga.setText("");
        Hari.setText("");
        Ttl_harga.setText("");
        Bayar.setText("");
    }//GEN-LAST:event_BatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotell_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotell_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotell_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotell_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotell_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JTextField Bayar;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Hari;
    private javax.swing.JComboBox<String> Kamar;
    private javax.swing.JButton Konfirmasi;
    private javax.swing.JTextField Ttl_harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
